import{a as v,S,i as a}from"./assets/vendor-DceEIEvX.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const P="50832143-3e18ca1c7d3ff8d3379931b93",q="https://pixabay.com/api/";async function h(s,r=1){const o={key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r},{data:n}=await v(q,{params:o});return n}const g=document.querySelector(".loader"),u=document.querySelector(".load-more-btn"),c=document.querySelector(".gallery");function p(s){return s.map(({webformatURL:r,largeImageURL:o,tags:n,likes:e,views:t,comments:i,downloads:w})=>`
<li class="gallery-item"><a href="${o}"><img src="${r}" alt="${n}">
<div class="info">
<p><b>Likes</b>${e}</p>
<p><b>Views</b>${t}</p>
<p><b>Comments</b>${i}</p>
<p><b>Downloads</b>${w}</p>
</div>
</a></li>
    `).join("")}function y(){g.classList.remove("hidden")}function b(){g.classList.add("hidden")}function B(){u.classList.remove("load-more-btn-hidden")}function f(){u.classList.add("load-more-btn-hidden")}function M(){c.innerHTML=""}const $=document.querySelector(".form");let L=new S(".gallery a"),l=1,d="",m=0;$.addEventListener("submit",async s=>{s.preventDefault();const r=s.currentTarget.elements["search-text"].value.trim();if(!r){a.warning({message:"Please enter a search term!"});return}d=r,l=1,M(),y(),f();try{const o=await h(d,l);m=o.totalHits,o.hits.length===0?a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(c.insertAdjacentHTML("beforeend",p(o.hits)),L.refresh(),o.hits.length<m?B():(f(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})))}catch(o){console.log(o.message),a.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{b()}});u.addEventListener("click",E);async function E(){l++,y();try{const s=await h(d,l);c.insertAdjacentHTML("beforeend",p(s.hits)),L.refresh();const{height:r}=c.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch(s){console.log(s.message),a.error({message:"Failed to load more images. Please try again!",position:"topRight"})}finally{b()}}
//# sourceMappingURL=index.js.map
