import{a as w,S as v,i as c}from"./assets/vendor-DceEIEvX.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const S="50832143-3e18ca1c7d3ff8d3379931b93",P="https://pixabay.com/api/";async function m(s,r=1){const o={key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r},{data:i}=await w(P,{params:o});return i}const h=document.querySelector(".loader"),d=document.querySelector(".load-more-btn");function g(s){return s.map(({webformatURL:r,largeImageURL:o,tags:i,likes:e,views:t,comments:a,downloads:L})=>`
<li class="gallery-item"><a href="${o}"><img src="${r}" alt="${i}">
<div class="info">
<p><b>Likes</b>${e}</p>
<p><b>Views</b>${t}</p>
<p><b>Comments</b>${a}</p>
<p><b>Downloads</b>${L}</p>
</div>
</a></li>
    `).join("")}function p(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}function q(){d.classList.remove("load-more-btn-hidden")}function B(){d.classList.add("load-more-btn-hidden")}let b=new v(".gallery a");const l=document.querySelector(".gallery"),M=document.querySelector(".form");let n=1,u="",f=0;function $(){l.innerHTML=""}M.addEventListener("submit",async s=>{s.preventDefault();const r=s.currentTarget.elements["search-text"].value.trim();if(!r){c.warning({message:"Please enter a search term!"});return}u=r,n=1,$(),p(),B();try{const o=await m(u,n);f=o.totalHits,o.hits.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(l.insertAdjacentHTML("beforeend",g(o.hits)),b.refresh(),o.hits.length===15&&n*15<f&&q())}catch(o){console.log(o.message),c.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{y()}});d.addEventListener("click",E);async function E(){n++,p();try{const s=await m(u,n);l.insertAdjacentHTML("beforeend",g(s.hits)),b.refresh();const{height:r}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),n*15>=f&&(d.classList.add("load-more-btn-hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){console.log(s.message),c.error({message:"Failed to load more images. Please try again!",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
