import{a as S,S as q,i}from"./assets/vendor-DceEIEvX.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const M="50832143-3e18ca1c7d3ff8d3379931b93",B="https://pixabay.com/api/";async function h(s,t=1){const o={key:M,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t},{data:a}=await S(B,{params:o});return a}const g=document.querySelector(".loader"),f=document.querySelector(".load-more-btn"),m=document.querySelector(".gallery");function p(s,t){const o=s.map(({webformatURL:a,largeImageURL:e,tags:r,likes:c,views:w,comments:v,downloads:P})=>`
<li class="gallery-item"><a href="${e}"><img src="${a}" alt="${r}">
<div class="info">
<p><b>Likes</b> ${c}</p>
<p><b>Views</b> ${w}</p>
<p><b>Comments</b> ${v}</p>
<p><b>Downloads</b> ${P}</p>
</div>
</a></li>
    `).join("");m.insertAdjacentHTML("beforeend",o),t&&t.refresh()}function R(){g.classList.remove("hidden")}function y(){g.classList.add("hidden")}function $(){f.classList.remove("load-more-btn-hidden")}function l(){f.classList.add("load-more-btn-hidden")}function E(){m.innerHTML=""}const O=document.querySelector(".form");let b=new q(".gallery a"),n=1,d="",u=0;const L=15;O.addEventListener("submit",async s=>{s.preventDefault();const t=s.currentTarget.elements["search-text"].value.trim();if(!t){i.warning({message:"Please enter a search term!"});return}d=t,n=1,E(),R(),l();try{const o=await h(d,n);u=o.totalHits;const a=Math.ceil(u/L);o.hits.length===0?i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(p(o.hits,b),n<a?$():(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})))}catch(o){console.log(o.message),i.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{y()}});f.addEventListener("click",H);async function H(){n++;const s=Math.ceil(u/L);try{const t=await h(d,n);p(t.hits,b);const{height:o}=m.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),n>=s&&(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){console.log(t.message),i.error({message:"Failed to load more images. Please try again!",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
